import 'package:flutter/material.dart';

class HabitIconItem {
  final String id;
  final IconData icon;

  const HabitIconItem({
    required this.id,
    required this.icon,
  });
}

const List<HabitIconItem> habitIconsCatalog = [
  // Core / Symbols
  HabitIconItem(id: 'bolt', icon: Icons.bolt_rounded),
  HabitIconItem(id: 'star', icon: Icons.star_rounded),
  HabitIconItem(id: 'favorite', icon: Icons.favorite_rounded),
  HabitIconItem(id: 'wb_sunny', icon: Icons.wb_sunny_rounded),
  HabitIconItem(id: 'coffee', icon: Icons.coffee_rounded),
  HabitIconItem(id: 'music_note', icon: Icons.music_note_rounded),
  HabitIconItem(id: 'laptop', icon: Icons.laptop_rounded),
  HabitIconItem(id: 'menu_book', icon: Icons.menu_book_rounded),
  HabitIconItem(id: 'directions_walk', icon: Icons.directions_walk_rounded),
  HabitIconItem(id: 'directions_run', icon: Icons.directions_run_rounded),
  HabitIconItem(id: 'fitness_center', icon: Icons.fitness_center_rounded),
  HabitIconItem(id: 'self_improvement', icon: Icons.self_improvement_rounded),
  HabitIconItem(id: 'water_drop', icon: Icons.water_drop_rounded),
  HabitIconItem(id: 'bedtime', icon: Icons.bedtime_rounded),
  HabitIconItem(id: 'restaurant', icon: Icons.restaurant_rounded),
  HabitIconItem(id: 'work', icon: Icons.work_outline_rounded),
  HabitIconItem(id: 'school', icon: Icons.school_rounded),
  HabitIconItem(id: 'attach_money', icon: Icons.attach_money_rounded),
  HabitIconItem(id: 'alarm', icon: Icons.alarm_rounded),
  HabitIconItem(id: 'brush', icon: Icons.brush_rounded),
  HabitIconItem(id: 'task_alt', icon: Icons.task_alt_rounded),
  HabitIconItem(id: 'eco', icon: Icons.eco_rounded),
  HabitIconItem(id: 'cleaning_services', icon: Icons.cleaning_services_rounded),
  HabitIconItem(id: 'track_changes', icon: Icons.track_changes_rounded),
  HabitIconItem(id: 'timer', icon: Icons.timer_outlined),
  HabitIconItem(id: 'headphones', icon: Icons.headphones_rounded),
  HabitIconItem(id: 'pedal_bike', icon: Icons.pedal_bike_rounded),
  HabitIconItem(id: 'pool', icon: Icons.pool_rounded),
  HabitIconItem(id: 'spa', icon: Icons.spa_rounded),
  HabitIconItem(id: 'local_fire_department', icon: Icons.local_fire_department_rounded),
  // Sports & Activities
  HabitIconItem(id: 'sports_soccer', icon: Icons.sports_soccer_rounded),
  HabitIconItem(id: 'sports_basketball', icon: Icons.sports_basketball_rounded),
  HabitIconItem(id: 'sports_tennis', icon: Icons.sports_tennis_rounded),
  HabitIconItem(id: 'hiking', icon: Icons.hiking_rounded),
  HabitIconItem(id: 'skateboarding', icon: Icons.skateboarding_rounded),
  HabitIconItem(id: 'kayaking', icon: Icons.kayaking_rounded),
  HabitIconItem(id: 'sailing', icon: Icons.sailing_rounded),
  HabitIconItem(id: 'sports_gymnastics', icon: Icons.sports_gymnastics_rounded),
  HabitIconItem(id: 'sports_martial_arts', icon: Icons.sports_martial_arts_rounded),
  HabitIconItem(id: 'rowing', icon: Icons.rowing_rounded),
  // Arts & Creativity
  HabitIconItem(id: 'palette', icon: Icons.palette_rounded),
  HabitIconItem(id: 'camera_alt', icon: Icons.camera_alt_rounded),
  HabitIconItem(id: 'movie', icon: Icons.movie_rounded),
  HabitIconItem(id: 'piano', icon: Icons.piano_rounded),
  HabitIconItem(id: 'mic', icon: Icons.mic_rounded),
  HabitIconItem(id: 'draw', icon: Icons.draw_rounded),
  HabitIconItem(id: 'architecture', icon: Icons.architecture_rounded),
  HabitIconItem(id: 'auto_stories', icon: Icons.auto_stories_rounded),
  HabitIconItem(id: 'edit_note', icon: Icons.edit_note_rounded),
  HabitIconItem(id: 'style', icon: Icons.style_rounded),
  // Intellect & Mind
  HabitIconItem(id: 'lightbulb', icon: Icons.lightbulb_outline_rounded),
  HabitIconItem(id: 'psychology', icon: Icons.psychology_rounded),
  HabitIconItem(id: 'science', icon: Icons.science_rounded),
  HabitIconItem(id: 'calculate', icon: Icons.calculate_rounded),
  HabitIconItem(id: 'language', icon: Icons.language_rounded),
  HabitIconItem(id: 'public', icon: Icons.public_rounded),
  HabitIconItem(id: 'explore', icon: Icons.explore_rounded),
  HabitIconItem(id: 'flight_takeoff', icon: Icons.flight_takeoff_rounded),
  HabitIconItem(id: 'code', icon: Icons.code_rounded),
  HabitIconItem(id: 'terminal', icon: Icons.terminal_rounded),
  // Nature & Pets
  HabitIconItem(id: 'park', icon: Icons.park_rounded),
  HabitIconItem(id: 'forest', icon: Icons.forest_rounded),
  HabitIconItem(id: 'pets', icon: Icons.pets_rounded),
  HabitIconItem(id: 'local_florist', icon: Icons.local_florist_rounded),
  HabitIconItem(id: 'grass', icon: Icons.grass_rounded),
  HabitIconItem(id: 'terrain', icon: Icons.terrain_rounded),
  HabitIconItem(id: 'wb_twilight', icon: Icons.wb_twilight_rounded),
  HabitIconItem(id: 'nights_stay', icon: Icons.nights_stay_rounded),
  HabitIconItem(id: 'cloud', icon: Icons.cloud_rounded),
  HabitIconItem(id: 'umbrella', icon: Icons.umbrella_rounded),
  // Trophies & Goals
  HabitIconItem(id: 'emoji_events', icon: Icons.emoji_events_rounded),
  HabitIconItem(id: 'workspace_premium', icon: Icons.workspace_premium_rounded),
  HabitIconItem(id: 'military_tech', icon: Icons.military_tech_rounded),
  HabitIconItem(id: 'shield', icon: Icons.shield_rounded),
  HabitIconItem(id: 'flag', icon: Icons.flag_rounded),
  HabitIconItem(id: 'rocket_launch', icon: Icons.rocket_launch_rounded),
  HabitIconItem(id: 'diamond', icon: Icons.diamond_rounded),
  HabitIconItem(id: 'savings', icon: Icons.savings_rounded),
  HabitIconItem(id: 'account_balance', icon: Icons.account_balance_rounded),
  HabitIconItem(id: 'credit_card', icon: Icons.credit_card_rounded),
  // Food & Nutrition
  HabitIconItem(id: 'shopping_bag', icon: Icons.shopping_bag_rounded),
  HabitIconItem(id: 'local_grocery_store', icon: Icons.local_grocery_store_rounded),
  HabitIconItem(id: 'fastfood', icon: Icons.fastfood_rounded),
  HabitIconItem(id: 'lunch_dining', icon: Icons.lunch_dining_rounded),
  HabitIconItem(id: 'local_pizza', icon: Icons.local_pizza_rounded),
  HabitIconItem(id: 'local_bar', icon: Icons.local_bar_rounded),
  HabitIconItem(id: 'local_cafe', icon: Icons.local_cafe_rounded),
  HabitIconItem(id: 'cookie', icon: Icons.cookie_rounded),
  HabitIconItem(id: 'cake', icon: Icons.cake_rounded),
  HabitIconItem(id: 'icecream', icon: Icons.icecream_rounded),
  // Health & Body
  HabitIconItem(id: 'local_pharmacy', icon: Icons.local_pharmacy_rounded),
  HabitIconItem(id: 'medication', icon: Icons.medication_rounded),
  HabitIconItem(id: 'healing', icon: Icons.healing_rounded),
  HabitIconItem(id: 'health_and_safety', icon: Icons.health_and_safety_rounded),
  HabitIconItem(id: 'monitor_heart', icon: Icons.monitor_heart_rounded),
  HabitIconItem(id: 'mood', icon: Icons.mood_rounded),
  HabitIconItem(id: 'sanitizer', icon: Icons.sanitizer_rounded),
  HabitIconItem(id: 'clean_hands', icon: Icons.clean_hands_rounded),
  HabitIconItem(id: 'air', icon: Icons.air_rounded),
  HabitIconItem(id: 'thermostat', icon: Icons.thermostat_rounded),
  // Home & Lifestyle
  HabitIconItem(id: 'home', icon: Icons.home_rounded),
  HabitIconItem(id: 'cottage', icon: Icons.cottage_rounded),
  HabitIconItem(id: 'bed', icon: Icons.bed_rounded),
  HabitIconItem(id: 'bathtub', icon: Icons.bathtub_rounded),
  HabitIconItem(id: 'weekend', icon: Icons.weekend_rounded),
  HabitIconItem(id: 'kitchen', icon: Icons.kitchen_rounded),
  HabitIconItem(id: 'yard', icon: Icons.yard_rounded),
  HabitIconItem(id: 'local_laundry_service', icon: Icons.local_laundry_service_rounded),
  HabitIconItem(id: 'handyman', icon: Icons.handyman_rounded),
  HabitIconItem(id: 'build', icon: Icons.build_rounded),
  // Tech & Communication
  HabitIconItem(id: 'phone_iphone', icon: Icons.phone_iphone_rounded),
  HabitIconItem(id: 'desktop_windows', icon: Icons.desktop_windows_rounded),
  HabitIconItem(id: 'videogame_asset', icon: Icons.videogame_asset_rounded),
  HabitIconItem(id: 'headset_mic', icon: Icons.headset_mic_rounded),
  HabitIconItem(id: 'lock', icon: Icons.lock_rounded),
  HabitIconItem(id: 'key', icon: Icons.key_rounded),
  HabitIconItem(id: 'mail', icon: Icons.mail_rounded),
  HabitIconItem(id: 'send', icon: Icons.send_rounded),
  HabitIconItem(id: 'chat_bubble', icon: Icons.chat_bubble_rounded),
  HabitIconItem(id: 'thumb_up', icon: Icons.thumb_up_rounded),
];

final Map<String, IconData> _iconLookupMap = {
  for (final item in habitIconsCatalog) item.id.toLowerCase(): item.icon,
  'walking': Icons.directions_walk_rounded,
  'running': Icons.directions_run_rounded,
  'workout': Icons.fitness_center_rounded,
  'gym': Icons.fitness_center_rounded,
  'coding': Icons.code_rounded,
  'reading': Icons.menu_book_rounded,
  'meditation': Icons.self_improvement_rounded,
  'water': Icons.water_drop_rounded,
  'sleep': Icons.bedtime_rounded,
  'food': Icons.restaurant_rounded,
  'music': Icons.music_note_rounded,
  'study': Icons.school_rounded,
  'money': Icons.attach_money_rounded,
  'finance': Icons.attach_money_rounded,
  'health': Icons.favorite_rounded,
  'goal': Icons.track_changes_rounded,
  'personal': Icons.eco_rounded,
  'cleaning': Icons.cleaning_services_rounded,
  'art': Icons.brush_rounded,
  'focus': Icons.task_alt_rounded,
};

IconData getHabitIcon(String? iconId) {
  if (iconId == null || iconId.isEmpty) {
    return Icons.bolt_rounded;
  }
  return _iconLookupMap[iconId.toLowerCase()] ?? Icons.bolt_rounded;
}
